/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package JogosLotoJogador;


import java.awt.FlowLayout;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bil
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTitlePanel = new javax.swing.JPanel();
        jTitulo = new javax.swing.JLabel();
        jRegrasLabel = new javax.swing.JLabel();
        jRegrasLabel2 = new javax.swing.JLabel();
        jPanelAtualNumeroSorteado = new javax.swing.JPanel();
        jButtonatuallNumeroSorteado = new javax.swing.JButton();
        jLabelatualNumeroSorteado = new javax.swing.JLabel();
        jBigLabelatualNumeroSorteado = new javax.swing.JLabel();
        jPanelNumerosSorteados = new javax.swing.JPanel();
        jButtonNumerosSorteados = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNumerosSorteados = new javax.swing.JList<>();
        jLabelNumerosSorteados = new javax.swing.JLabel();
        jPanelApostas = new javax.swing.JPanel();
        jLabelApostas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListApostas = new javax.swing.JList<>();
        jButtonAposta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setSize(new java.awt.Dimension(200, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTitlePanel.setBackground(new java.awt.Color(3, 36, 168));
        jTitlePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTitlePanel.setPreferredSize(new java.awt.Dimension(100, 100));
        jTitlePanel.setLayout(new java.awt.GridBagLayout());

        jTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("Jogo De Loto - Gestor de Sala");
        jTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        jTitlePanel.add(jTitulo, gridBagConstraints);

        jRegrasLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRegrasLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRegrasLabel.setText("Formula de recompensa de Apostas:");
        jRegrasLabel.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        jTitlePanel.add(jRegrasLabel, gridBagConstraints);

        jRegrasLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRegrasLabel2.setText("apostaFeita + SomaDe_apostas_nao_vencidas / (nº_de_nao_Vencedores + 1)");
        jRegrasLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        jTitlePanel.add(jRegrasLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jTitlePanel, gridBagConstraints);

        jPanelAtualNumeroSorteado.setBackground(new java.awt.Color(0, 51, 255));
        jPanelAtualNumeroSorteado.setLayout(new java.awt.GridBagLayout());

        jButtonatuallNumeroSorteado.setText("Sortear Número");
        jButtonatuallNumeroSorteado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonatuallNumeroSorteado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonatuallNumeroSorteadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        jPanelAtualNumeroSorteado.add(jButtonatuallNumeroSorteado, gridBagConstraints);

        jLabelatualNumeroSorteado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelatualNumeroSorteado.setText("Número Sorteado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanelAtualNumeroSorteado.add(jLabelatualNumeroSorteado, gridBagConstraints);

        jBigLabelatualNumeroSorteado.setFont(new java.awt.Font("Tahoma", 0, 120)); // NOI18N
        jBigLabelatualNumeroSorteado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBigLabelatualNumeroSorteado.setText("62");
        jBigLabelatualNumeroSorteado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanelAtualNumeroSorteado.add(jBigLabelatualNumeroSorteado, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanelAtualNumeroSorteado, gridBagConstraints);

        jPanelNumerosSorteados.setBackground(new java.awt.Color(213, 47, 96));
        jPanelNumerosSorteados.setLayout(new java.awt.GridBagLayout());

        jButtonNumerosSorteados.setText("Terminar Jogo");
        jButtonNumerosSorteados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumerosSorteadosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        jPanelNumerosSorteados.add(jButtonNumerosSorteados, gridBagConstraints);

        jListNumerosSorteados.setBackground(new java.awt.Color(193, 29, 77));
        jListNumerosSorteados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListNumerosSorteados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jListNumerosSorteados);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 4);
        jPanelNumerosSorteados.add(jScrollPane2, gridBagConstraints);

        jLabelNumerosSorteados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNumerosSorteados.setText("Números Sorteados:");
        jLabelNumerosSorteados.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelNumerosSorteados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanelNumerosSorteados.add(jLabelNumerosSorteados, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanelNumerosSorteados, gridBagConstraints);

        jPanelApostas.setBackground(new java.awt.Color(153, 0, 153));
        jPanelApostas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelApostas.setLayout(new java.awt.GridBagLayout());

        jLabelApostas.setBackground(new java.awt.Color(0, 102, 102));
        jLabelApostas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelApostas.setText("Apostas:");
        jLabelApostas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelApostas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanelApostas.add(jLabelApostas, gridBagConstraints);
        jLabelApostas.getAccessibleContext().setAccessibleName("Apostas:");
        jLabelApostas.getAccessibleContext().setAccessibleDescription("");

        jScrollPane1.setBorder(null);

        jListApostas.setBackground(new java.awt.Color(133, 1, 133));
        jListApostas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jListApostas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListApostas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListApostas.setFocusable(false);
        jListApostas.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jListApostas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 1);
        jPanelApostas.add(jScrollPane1, gridBagConstraints);

        jButtonAposta.setText("Adicionar Aposta");
        jButtonAposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApostaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        jPanelApostas.add(jButtonAposta, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanelApostas, gridBagConstraints);

        pack();
    }// </editor-fold>                        

    private void jButtonApostaActionPerformed(java.awt.event.ActionEvent evt) {                                              
//        CriarJogador player = new CriarJogador();
//        player.setVisible(true);
    }                                             

    private void jButtonNumerosSorteadosActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    private void jButtonatuallNumeroSorteadoActionPerformed(java.awt.event.ActionEvent evt) {                                                            
    
       
    }                                                           
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jBigLabelatualNumeroSorteado;
    private javax.swing.JButton jButtonAposta;
    private javax.swing.JButton jButtonNumerosSorteados;
    private javax.swing.JButton jButtonatuallNumeroSorteado;
    private javax.swing.JLabel jLabelApostas;
    private javax.swing.JLabel jLabelNumerosSorteados;
    private javax.swing.JLabel jLabelatualNumeroSorteado;
    private javax.swing.JList<String> jListApostas;
    private javax.swing.JList<String> jListNumerosSorteados;
    private javax.swing.JPanel jPanelApostas;
    private javax.swing.JPanel jPanelAtualNumeroSorteado;
    private javax.swing.JPanel jPanelNumerosSorteados;
    private javax.swing.JLabel jRegrasLabel;
    private javax.swing.JLabel jRegrasLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jTitlePanel;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration                   

}
